name: crossfit-board CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: CI/CD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Grant execute permission for gradlew
        run: chmod +x ./crossfit-back/gradlew
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt' # See 'Supported distributions' for available options
      - name: List directory
        run: ls ./crossfit-back
      - name: Change directory and build
        working-directory: ./crossfit-back
        run: ./gradlew crossfit-board:build
      - name: DockerHub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker Image Build
        working-directory: ./crossfit-back/crossfit-board
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_CROSSFIT_BOARD_IMAGE_NAME }} .

      - name: DockerHub Push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_CROSSFIT_BOARD_IMAGE_NAME }}

      - name: trigger jenkins job.
        uses: appleboy/jenkins-action@master
        with:
          url: ${{ secrets.JENKINS_URL }}
          user: ${{ secrets.JENKINS_USER }}
          token: ${{ secrets.JENKINS_TOKEN }}
          job: ${{ secrets.JENKINS_CROSSFIT_BOARD_JOB_NAME }}
