name: crossfit-board CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: CI/CD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Grant execute permission for gradlew
        run: chmod +x ./crossfit-back/gradlew
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt' # See 'Supported distributions' for available options
      - name: List directory
        run: ls ./crossfit-back
      - name: Change directory and build
        working-directory: ./crossfit-back
        run: ./gradlew crossfit-board:build
      - name: DockerHub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker Image Build
        run: docker build -f crossfit-board/Dockerfile -t $DOCKER_IMAGE crossfit-board/

      - name: DockerHub Push
        run: docker push $DOCKER_IMAGE
